FROM node:24-alpine AS builder

WORKDIR /app

COPY ./package*.json ./tsconfig.json ./vite.config.ts ./public ./

RUN npm config set strict-ssl false && \ 
    npm ci && \ 
    npm config set strict-ssl true

COPY . .

FROM node:24-alpine as stage

RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64 && \
    chmod +x /usr/local/bin/dumb-init

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json /app/tsconfig.json /app/vite.config.ts /app/public ./
COPY --from=builder /app/app ./app



EXPOSE 5173
ENTRYPOINT ["dumb-init", "--"]
CMD [ "npm", "run", "dev" ]



# FROM node:24-alpine AS production-dependencies-env

# WORKDIR /app
# RUN npm ci --omit=dev

# FROM node:24-alpine AS build-env
# COPY . /app/
# COPY --from=development-dependencies-env /app/node_modules /app/node_modules
# WORKDIR /app
# RUN npm run build

# FROM node:24-alpine
# COPY ./package.json package-lock.json /app/
# COPY --from=production-dependencies-env /app/node_modules /app/node_modules
# COPY --from=build-env /app/build /app/build
# WORKDIR /app
# CMD ["npm", "run", "start"]